name: GitHub Profile Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # daily run
  workflow_dispatch:

jobs:
  profile-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 15
          base: "classic"
