name: GitHub Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          base: ""
          plugin_tools: yes
          plugin_tools_limit: 32
          plugin_tools_sections: "most-used"
          plugin_tools_sort: "favorite" 
          
          user: Mushfiqur-Rahman-Robin
          config_timezone: Asia/Dhaka
          filename: metrics.tools.svg