name: Minimal Workflow Test

on:
  workflow_dispatch: # Manual trigger only

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run a simple command
      run: echo "This workflow is working!"